package JFrameN;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import Controlador.PedidosController;
import Modelo.Productos;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author usuario
 */
public class MenuCombos extends javax.swing.JInternalFrame {
    private PedidosController pedidoController;


    /**
     * Creates new form MenuCombos
     */
    public MenuCombos(PedidosController pedidoController) {
        this.pedidoController = pedidoController;
        initComponents();
        
          this.setClosable(true);
        this.setMaximizable(true);
        this.setIconifiable(true);
        this.setResizable(true);
        
       SwingUtilities.invokeLater(() -> {
        this.Imagen(this.LblImgaen, "src/Img/Fondo.jpg");
        this.Imagen(this.LblImgaen1, "src/Img/Comb.png");
        this.Imagen(this.LblImgaen2, "src/Img/Combos.png");
       });
    }

    private ImageIcon imagen;
    private Icon icono;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LblImgaen1 = new javax.swing.JLabel();
        BtnBirria = new javax.swing.JButton();
        btnAsada = new javax.swing.JButton();
        BtnCanasta = new javax.swing.JButton();
        BtnAgregar = new javax.swing.JButton();
        BtnRegresar = new javax.swing.JButton();
        LblImgaen2 = new javax.swing.JLabel();
        LblImgaen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(LblImgaen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 580, 110));

        BtnBirria.setBackground(new java.awt.Color(255, 102, 0));
        BtnBirria.setFont(new java.awt.Font("SimSun-ExtG", 2, 36)); // NOI18N
        BtnBirria.setForeground(new java.awt.Color(0, 51, 153));
        BtnBirria.setText("Porsion de Birria");
        BtnBirria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBirriaActionPerformed(evt);
            }
        });
        jPanel1.add(BtnBirria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 350, 70));

        btnAsada.setBackground(new java.awt.Color(255, 102, 0));
        btnAsada.setFont(new java.awt.Font("SimSun-ExtB", 2, 36)); // NOI18N
        btnAsada.setForeground(new java.awt.Color(0, 51, 153));
        btnAsada.setText("Porsion de Asada");
        btnAsada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsadaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAsada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 350, 70));

        BtnCanasta.setBackground(new java.awt.Color(255, 102, 0));
        BtnCanasta.setFont(new java.awt.Font("SimSun-ExtB", 2, 24)); // NOI18N
        BtnCanasta.setForeground(new java.awt.Color(0, 51, 153));
        BtnCanasta.setText("Porsion de canasta");
        BtnCanasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCanastaActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCanasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 350, 70));

        BtnAgregar.setBackground(new java.awt.Color(153, 0, 0));
        BtnAgregar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        BtnAgregar.setForeground(new java.awt.Color(255, 204, 0));
        BtnAgregar.setText("Agregar ");
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 220, 50));

        BtnRegresar.setBackground(new java.awt.Color(153, 0, 0));
        BtnRegresar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        BtnRegresar.setForeground(new java.awt.Color(255, 204, 0));
        BtnRegresar.setText("Regresar");
        BtnRegresar.setToolTipText("");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 510, 180, 40));
        jPanel1.add(LblImgaen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 380, 250));
        jPanel1.add(LblImgaen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBirriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBirriaActionPerformed
    Productos comboBirria = new Productos(
            1,
            "Combo Birria", 
            2,
            150.00, 
           " COMBO: 12 tacos de birria, refresco y porción de papas"
        );
        
        // Agregar al pedido
        pedidoController.agregarPedido(comboBirria);
        
        // Mostrar confirmación al usuario
        JOptionPane.showMessageDialog(
            this, 
            "Combo Birria agregado al pedido", 
            "Producto Agregado", 
            JOptionPane.INFORMATION_MESSAGE
        );
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBirriaActionPerformed
    private void btnAsadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsadaActionPerformed
Productos ComboAsada = new Productos(
            2,
            "Combo Asada", 
            1,
            125.00, 
            "COMBO: 12 tacos de birria, refresco y porción de papas"
        );
        
        // Agregar al pedido
        pedidoController.agregarPedido(ComboAsada);
        
        // Mostrar confirmación al usuario
        JOptionPane.showMessageDialog(
            this, 
            "Combo Asada agregado al pedido", 
            "Producto Agregado", 
            JOptionPane.INFORMATION_MESSAGE
        );
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAsadaActionPerformed

    private void BtnCanastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCanastaActionPerformed
    Productos ComboCanasta = new Productos(
            3,
            "Combo Canasta", 
            2,
            140.00, 
            "COMBO: 12 tacos de birria, refresco y porción de papas"
        );
        
        // Agregar al pedido
        pedidoController.agregarPedido(ComboCanasta);
        
        // Mostrar confirmación al usuario
        JOptionPane.showMessageDialog(
            this, 
            "Combo Canasta agregado al pedido", 
            "Producto Agregado", 
            JOptionPane.INFORMATION_MESSAGE
        );
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCanastaActionPerformed

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
 int opcion = JOptionPane.showConfirmDialog(
        this, 
        "¿Desea salir del menu de combos?", 
        "Confirmar salida", 
        JOptionPane.YES_NO_OPTION
    );
    
    if (opcion == JOptionPane.YES_OPTION) {
        this.dispose();      
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
 StringBuilder resumen = new StringBuilder("Productos en tu pedido:\n");
    for (Productos p : pedidoController.getProductosSeleccionados()) {
        resumen.append("- ").append(p.getNombre())
               .append(" $").append(p.getPrecio()).append("\n");
    }
    resumen.append("\nTotal: $").append(pedidoController.getTotal());
    
    JOptionPane.showMessageDialog(
        this, 
        resumen.toString(), 
        "Resumen de Pedido", 
        JOptionPane.INFORMATION_MESSAGE
    );
    
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
        
    private void Imagen(JLabel lbl, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(lbl.getWidth(), 
                        lbl.getHeight(), 
                        Image.SCALE_DEFAULT)
        );
        lbl.setIcon(this.icono);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnBirria;
    private javax.swing.JButton BtnCanasta;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JLabel LblImgaen;
    private javax.swing.JLabel LblImgaen1;
    private javax.swing.JLabel LblImgaen2;
    private javax.swing.JButton btnAsada;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
