package JFrameN;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import Controlador.PedidosController;
import Controlador.ProductosController;
import Modelo.Productos;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author usuario
 */
public class MenuExtras extends javax.swing.JInternalFrame {
private PedidosController pedidoController;

    public MenuExtras(PedidosController pedidoController) {
        this.pedidoController = pedidoController;
        initComponents();
    }
    /**
     * Creates new form MenuExtras
     */
    public MenuExtras() {
        initComponents();
         this.setClosable(true);
        this.setMaximizable(true);
        this.setIconifiable(true);
        this.setResizable(true);
         SwingUtilities.invokeLater(() -> {
        this.Imagen(this.LblImgaen, "src/Img/Fondo.jpg");
        this.Imagen(this.LblImgaen1, "src/Img/Extras.png");
        this.Imagen(this.LblImgaen2, "src/Img/Bebidas.png");
        this.Imagen(this.LblImgaen3, "src/Img/Papas.png");
        this.Imagen(this.LblImgaen4, "src/Img/Postre.png");
         });
    }

    private ImageIcon imagen;
    private Icon icono;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LblImgaen1 = new javax.swing.JLabel();
        BtnRegresar = new javax.swing.JButton();
        Btnbebidas = new javax.swing.JButton();
        btnpapas = new javax.swing.JButton();
        Btnpostres = new javax.swing.JButton();
        BtnAgregar = new javax.swing.JButton();
        LblImgaen2 = new javax.swing.JLabel();
        LblImgaen3 = new javax.swing.JLabel();
        LblImgaen4 = new javax.swing.JLabel();
        LblImgaen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(LblImgaen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 480, 100));

        BtnRegresar.setBackground(new java.awt.Color(153, 0, 0));
        BtnRegresar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        BtnRegresar.setForeground(new java.awt.Color(255, 204, 0));
        BtnRegresar.setText("Regresar");
        BtnRegresar.setToolTipText("");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 530, 180, 40));

        Btnbebidas.setBackground(new java.awt.Color(255, 102, 0));
        Btnbebidas.setFont(new java.awt.Font("SimSun-ExtG", 2, 36)); // NOI18N
        Btnbebidas.setForeground(new java.awt.Color(0, 51, 153));
        Btnbebidas.setText("Bebidas");
        Btnbebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnbebidasActionPerformed(evt);
            }
        });
        jPanel1.add(Btnbebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 350, 70));

        btnpapas.setBackground(new java.awt.Color(255, 102, 0));
        btnpapas.setFont(new java.awt.Font("SimSun-ExtB", 2, 36)); // NOI18N
        btnpapas.setForeground(new java.awt.Color(0, 51, 153));
        btnpapas.setText("Porsion de papas");
        btnpapas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpapasActionPerformed(evt);
            }
        });
        jPanel1.add(btnpapas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 350, 70));

        Btnpostres.setBackground(new java.awt.Color(255, 102, 0));
        Btnpostres.setFont(new java.awt.Font("SimSun-ExtB", 2, 24)); // NOI18N
        Btnpostres.setForeground(new java.awt.Color(0, 51, 153));
        Btnpostres.setText("Postres");
        Btnpostres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnpostresActionPerformed(evt);
            }
        });
        jPanel1.add(Btnpostres, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 350, 70));

        BtnAgregar.setBackground(new java.awt.Color(153, 0, 0));
        BtnAgregar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        BtnAgregar.setForeground(new java.awt.Color(255, 204, 0));
        BtnAgregar.setText("Agregar ");
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 220, 50));
        jPanel1.add(LblImgaen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 220, 150));
        jPanel1.add(LblImgaen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 240, 170));
        jPanel1.add(LblImgaen4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 250, 140));
        jPanel1.add(LblImgaen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 731, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnbebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnbebidasActionPerformed
    Productos bebida = new Productos(
            5,
            "Bebida", 
            1,
            15.00, 
            "EXTRA: Refrescante agua fria"
        );
        
        pedidoController.agregarPedido(bebida);
        
        JOptionPane.showMessageDialog(
            this, 
            "Bebida agregada al pedido", 
            "Producto Agregado", 
            JOptionPane.INFORMATION_MESSAGE
        );
      
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnbebidasActionPerformed

    private void btnpapasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpapasActionPerformed
      Productos papas = new Productos(
              6,
            "Porción de Papas", 
              2,
            25.50, 
            "EXTRA: Deliciosas papas a la francesa con aderezo"
        );
        
        pedidoController.agregarPedido(papas);
        
        JOptionPane.showMessageDialog(
            this, 
            "Porción de Papas agregada al pedido", 
            "Producto Agregado", 
            JOptionPane.INFORMATION_MESSAGE
        );
      
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpapasActionPerformed

 

    private void BtnpostresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnpostresActionPerformed
      Productos tiramisu = new Productos(
             4,
            "Tiramisu", 
            3,
            30.50, 
            "EXTRA: un Delicioso postre para alegrar el Dia"
        );
        
        pedidoController.agregarPedido(tiramisu);
        
        JOptionPane.showMessageDialog(
            this, 
            "Tiramisu agregada al pedido", 
            "Producto Agregado", 
            JOptionPane.INFORMATION_MESSAGE
        );
      
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnpostresActionPerformed

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
 StringBuilder resumen = new StringBuilder("Productos en tu pedido:\n");
    for (Productos p : pedidoController.getProductosSeleccionados()) {
        resumen.append("- ").append(p.getNombre())
               .append(" Q").append(p.getPrecio()).append("\n");
    }
    resumen.append("\nTotal: Q").append(pedidoController.getTotal());
    
    JOptionPane.showMessageDialog(
        this, 
        resumen.toString(), 
        "Resumen de Pedido", 
        JOptionPane.INFORMATION_MESSAGE
    );
    
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
    int opcion = JOptionPane.showConfirmDialog(
        this, 
        "¿Desea salir del menu de extras", 
        "Confirmar salida", 
        JOptionPane.YES_NO_OPTION
    );
    
    if (opcion == JOptionPane.YES_OPTION) {
        this.dispose();      
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    private void Imagen(JLabel lbl, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(lbl.getWidth(), 
                        lbl.getHeight(), 
                        Image.SCALE_DEFAULT)
        );
        lbl.setIcon(this.icono);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JButton Btnbebidas;
    private javax.swing.JButton Btnpostres;
    private javax.swing.JLabel LblImgaen;
    private javax.swing.JLabel LblImgaen1;
    private javax.swing.JLabel LblImgaen2;
    private javax.swing.JLabel LblImgaen3;
    private javax.swing.JLabel LblImgaen4;
    private javax.swing.JButton btnpapas;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
