package JFrameN;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import Controlador.PedidosController;
import Modelo.Productos;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author usuario
 */
public class MenuPersonales extends javax.swing.JInternalFrame {
    private PedidosController pedidoController;
  
    public MenuPersonales(PedidosController pedidoController) {
         this.pedidoController = pedidoController;
        initComponents();
        this.setClosable(true);
        this.setMaximizable(true);
        this.setIconifiable(true);
        this.setResizable(true);
       // this.setLocationRelativeTo(this);
       SwingUtilities.invokeLater(() -> {
        this.Imagen(this.LblImgaen, "src/Img/Fondo.jpg");
        this.Imagen(this.LblImgaen1, "src/Img/Perso.png");
        this.Imagen(this.LblImgaen2, "src/Img/Birria.png");
        this.Imagen(this.LblImgaen3, "src/Img/Asada.png");
        this.Imagen(this.LblImgaen4, "src/Img/Canasta.png");
       });
    }

    private ImageIcon imagen;
    private Icon icono;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LblImgaen2 = new javax.swing.JLabel();
        LblImgaen4 = new javax.swing.JLabel();
        LblImgaen3 = new javax.swing.JLabel();
        BtnCanasta = new javax.swing.JButton();
        LblImgaen1 = new javax.swing.JLabel();
        BtnBirria = new javax.swing.JButton();
        btnAsada = new javax.swing.JButton();
        BtnRegresar = new javax.swing.JButton();
        BtnAgregar = new javax.swing.JButton();
        LblImgaen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(LblImgaen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 320, 160));
        jPanel1.add(LblImgaen4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 270, 150));
        jPanel1.add(LblImgaen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 320, 160));

        BtnCanasta.setBackground(new java.awt.Color(255, 102, 0));
        BtnCanasta.setFont(new java.awt.Font("SimSun-ExtB", 2, 24)); // NOI18N
        BtnCanasta.setForeground(new java.awt.Color(0, 51, 153));
        BtnCanasta.setText("Porsion de canasta");
        BtnCanasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCanastaActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCanasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 350, 70));
        jPanel1.add(LblImgaen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 630, 110));

        BtnBirria.setBackground(new java.awt.Color(255, 102, 0));
        BtnBirria.setFont(new java.awt.Font("SimSun-ExtG", 2, 36)); // NOI18N
        BtnBirria.setForeground(new java.awt.Color(0, 51, 153));
        BtnBirria.setText("Porsion de Birria");
        BtnBirria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBirriaActionPerformed(evt);
            }
        });
        jPanel1.add(BtnBirria, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 350, 70));

        btnAsada.setBackground(new java.awt.Color(255, 102, 0));
        btnAsada.setFont(new java.awt.Font("SimSun-ExtB", 2, 36)); // NOI18N
        btnAsada.setForeground(new java.awt.Color(0, 51, 153));
        btnAsada.setText("Porsion de Asada");
        btnAsada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsadaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAsada, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 350, 70));

        BtnRegresar.setBackground(new java.awt.Color(153, 0, 0));
        BtnRegresar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        BtnRegresar.setForeground(new java.awt.Color(255, 204, 0));
        BtnRegresar.setText("Regresar");
        BtnRegresar.setToolTipText("");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 480, 180, 40));

        BtnAgregar.setBackground(new java.awt.Color(153, 0, 0));
        BtnAgregar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        BtnAgregar.setForeground(new java.awt.Color(255, 204, 0));
        BtnAgregar.setText("Agregar ");
        jPanel1.add(BtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 220, 50));
        jPanel1.add(LblImgaen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCanastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCanastaActionPerformed
       Productos Canasta = new Productos(
               8,
            "Porcion de Canasta", 
               1,
            40.00, 
            "PERSONAL: 3 tacos de carne de res  con salsa de aguacate y cilantro"
        );
        
        // Agregar al pedido
        pedidoController.agregarPedido(Canasta);
        
        // Mostrar confirmación al usuario
        JOptionPane.showMessageDialog(
            this, 
            "Porcion de Canasta agregados al pedido", 
            "Producto Agregado", 
            JOptionPane.INFORMATION_MESSAGE
        );
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCanastaActionPerformed

    private void BtnBirriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBirriaActionPerformed
   Productos Birria = new Productos(
           7,
            "Porcion de Birria", 
           2,
            60.00, 
            "PERSONAL: 3 tacos de carne birria con queso, cilantro y salsas"
        );
        
        // Agregar al pedido
        pedidoController.agregarPedido(Birria);
        
        // Mostrar confirmación al usuario
        JOptionPane.showMessageDialog(
            this, 
            "Porcion de Birria agregados al pedido", 
            "Producto Agregado", 
            JOptionPane.INFORMATION_MESSAGE
        );
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBirriaActionPerformed

    private void btnAsadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsadaActionPerformed
    Productos tacosAsada = new Productos(
            8,
            "Tacos de Asada", 
            4,
            45.00, 
            "PERSONAL: 3 tacos de carne asada con cebolla, cilantro y salsas"
        );
        
        // Agregar al pedido
        pedidoController.agregarPedido(tacosAsada);
        
        // Mostrar confirmación al usuario
        JOptionPane.showMessageDialog(
            this, 
            "Tacos de Asada agregados al pedido", 
            "Producto Agregado", 
            JOptionPane.INFORMATION_MESSAGE
        );
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAsadaActionPerformed

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
 int opcion = JOptionPane.showConfirmDialog(
        this, 
        "¿Desea salir del menu personal?", 
        "Confirmar salida", 
        JOptionPane.YES_NO_OPTION
    );
    
    if (opcion == JOptionPane.YES_OPTION) {
        this.dispose();      
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
   
    
     private void Imagen(JLabel lbl, String ruta){
        this.imagen = new ImageIcon(ruta);
        int width = lbl.getWidth() <= 0 ? imagen.getIconWidth() : lbl.getWidth();
        int height = lbl.getHeight() <= 0 ? imagen.getIconHeight() : lbl.getHeight();
    
        this.icono = new ImageIcon(
        this.imagen.getImage().getScaledInstance(width,height,Image.SCALE_SMOOTH));
        lbl.setIcon(this.icono);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnBirria;
    private javax.swing.JButton BtnCanasta;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JLabel LblImgaen;
    private javax.swing.JLabel LblImgaen1;
    private javax.swing.JLabel LblImgaen2;
    private javax.swing.JLabel LblImgaen3;
    private javax.swing.JLabel LblImgaen4;
    private javax.swing.JButton btnAsada;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
