/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrameN;

import Controlador.ReportesController;
import Modelo.Reportes;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Date;
import java.util.Map;
/**
 *
 * @author Gabriela
 */
public class ReportesJinterno extends javax.swing.JFrame {
      private final ReportesController controlador = new ReportesController();
    private final DefaultTableModel modeloTabla = new DefaultTableModel(new Object[]{
        "Fecha", "Usuario", "Producto", "Cantidad", "Total"
    }, 0); 

    /**
     * Creates new form ReportesJinterno
     */
    public ReportesJinterno() {
        initComponents();
        scrollTabla.setModel(modeloTabla);
        cargarComboboxUsuarios();
        cargarComboboxProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        lblFechaInicio = new javax.swing.JLabel();
        lblFechaFin = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JTextField();
        txtFechaFin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        cbUsuario = new javax.swing.JComboBox<>();
        lblProducto = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        scrollTabla = new javax.swing.JTable();
        btnExportarPDF = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnMasVendidos = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));

        lblFechaInicio.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblFechaInicio.setForeground(new java.awt.Color(0, 0, 153));
        lblFechaInicio.setText("Fecha inicio (dd/mm/yyyy)");

        lblFechaFin.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblFechaFin.setForeground(new java.awt.Color(0, 0, 153));
        lblFechaFin.setText("Fecha Fin");

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("La Taquiza");

        lblUsuario.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 0, 153));
        lblUsuario.setText("Usuario");

        cbUsuario.setBackground(new java.awt.Color(255, 255, 153));
        cbUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblProducto.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblProducto.setForeground(new java.awt.Color(0, 0, 153));
        lblProducto.setText("Producto");

        jComboBox2.setBackground(new java.awt.Color(255, 255, 153));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnBuscar.setBackground(new java.awt.Color(0, 153, 204));
        btnBuscar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        scrollTabla.setAutoCreateRowSorter(true);
        scrollTabla.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        scrollTabla.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        scrollTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(scrollTabla);

        btnExportarPDF.setBackground(new java.awt.Color(0, 204, 51));
        btnExportarPDF.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        btnExportarPDF.setText("📄Exportar a PDF");
        btnExportarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarPDFActionPerformed(evt);
            }
        });

        btnImprimir.setBackground(new java.awt.Color(0, 153, 204));
        btnImprimir.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        btnImprimir.setText("🖨 ️Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnMasVendidos.setBackground(new java.awt.Color(255, 102, 0));
        btnMasVendidos.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        btnMasVendidos.setText("📊 Ver más vendidos");
        btnMasVendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasVendidosActionPerformed(evt);
            }
        });

        btnReturn.setBackground(new java.awt.Color(153, 255, 153));
        btnReturn.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        btnReturn.setText("Regresar");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnExportarPDF)
                        .addGap(29, 29, 29)
                        .addComponent(btnImprimir)
                        .addGap(18, 18, 18)
                        .addComponent(btnMasVendidos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(lblProducto)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnBuscar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnReturn)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addComponent(lblFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(326, 326, 326))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)
                        .addGap(79, 79, 79)
                        .addComponent(lblFechaInicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFechaFin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsuario)
                            .addComponent(cbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProducto)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExportarPDF)
                    .addComponent(btnImprimir)
                    .addComponent(btnReturn)
                    .addComponent(btnMasVendidos))
                .addGap(148, 148, 148))
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void cargarComboboxUsuarios() {
        // Implementar lógica para cargar usuarios desde la base de datos
        cbUsuario.removeAllItems();
        cbUsuario.addItem("Todos"); // Opción por defecto
        cbUsuario.addItem("Usuario1");
        cbUsuario.addItem("Usuario2");
        // Agregar más usuarios según sea necesario
    }
    
    private Date parseFecha(String fechaStr) throws ParseException {
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        return formato.parse(fechaStr);
    }
    
    private void cargarComboboxProductos() {
        // Implementar lógica para cargar productos desde la base de datos
        jComboBox2.removeAllItems();
        jComboBox2.addItem("Todos"); // Opción por defecto
        jComboBox2.addItem("Producto1");
        jComboBox2.addItem("Producto2");
        // Agregar más productos según sea necesario
    }
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
         try {
        if (txtFechaInicio.getText().isEmpty() || txtFechaFin.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar ambas fechas", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Date fechaInicio = parseFecha(txtFechaInicio.getText());
        Date fechaFin = parseFecha(txtFechaFin.getText());

        // Obtener datos extendidos
        Map<String, Object> resumen = controlador.generarResumenVentas(fechaInicio, fechaFin);
        
        // Mostrar en tabla
        mostrarEnTabla((List<Reportes>) resumen.get("ventas"));
        
        // Mostrar información adicional
        String mensaje = "Resumen de ventas:\n" +
                         "Total en ventas: Q" + resumen.get("totalVentas") + "\n" +
                         "Total productos vendidos: " + resumen.get("totalProductos") + "\n" +
                         "Usuarios con ventas: " + String.join(", ", (List<String>)resumen.get("usuariosActivos"));
        
        JOptionPane.showMessageDialog(this, mensaje, "Resumen", JOptionPane.INFORMATION_MESSAGE);
        
    } catch (ParseException e) {
        JOptionPane.showMessageDialog(this, "Formato de fecha incorrecto. Use dd/mm/yyyy", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al buscar reportes: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
// TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
    String usuario = (String) cbUsuario.getSelectedItem();
    List<Reportes> datos = controlador.obtenerPorUsuario(usuario);
    controlador.imprimirReporte(datos, "Reporte por Usuario");
    JOptionPane.showMessageDialog(this, "Reporte enviado a impresión.");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnMasVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasVendidosActionPerformed
    List<Reportes> datos = controlador.obtenerMasVendidos();
    mostrarEnTabla(datos);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMasVendidosActionPerformed

    private void btnExportarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarPDFActionPerformed
    try {
            if (txtFechaInicio.getText().isEmpty() || txtFechaFin.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe ingresar ambas fechas para exportar", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            Date fechaInicio = parseFecha(txtFechaInicio.getText());
            Date fechaFin = parseFecha(txtFechaFin.getText());
            
             if (fechaInicio.after(fechaFin)) {
            JOptionPane.showMessageDialog(this, "La fecha de inicio debe ser anterior a la fecha fin", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

            List<Reportes> datos = controlador.obtenerPorFecha(fechaInicio, fechaFin);
            
            if (datos.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hay datos para el rango de fechas seleccionado", "Información", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        
            String nombreArchivo = "reporte_ventas_" + new SimpleDateFormat("yyyyMMdd").format(new Date()) + ".pdf";
          controlador.exportarPDF(datos, nombreArchivo, "Reporte de Ventas", fechaInicio, fechaFin);
        
            JOptionPane.showMessageDialog(this, "Reporte exportado a PDF: " + nombreArchivo, "Éxito", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Formato de fecha incorrecto. Use dd/mm/yyyy", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al exportar a PDF: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    // TODO add your handling code here:
    }//GEN-LAST:event_btnExportarPDFActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
     int opcion = JOptionPane.showConfirmDialog(
        this, 
        "¿Desea salir de la gestión de Reportes?", 
        "Confirmar salida", 
        JOptionPane.YES_NO_OPTION
    );
    
    if (opcion == JOptionPane.YES_OPTION) {
        // En una aplicación real, aquí iría la lógica para volver al menú principal
        // Por ahora simplemente cerraremos la ventana
        this.dispose();
        
        // Si tuvieras un menú principal, sería algo como:
        // new MenuPrincipal().setVisible(true);
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReturnActionPerformed
   
    private void mostrarEnTabla(List<Reportes> datos) {
        modeloTabla.setRowCount(0);
        for (Reportes rep : datos) {
            modeloTabla.addRow(new Object[]{
                rep.getFecha(),
                rep.getUsuario(),
                rep.getProducto(),
                rep.getCantidad(),
                rep.getTotal()
            });
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportesJinterno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportesJinterno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportesJinterno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportesJinterno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportesJinterno().setVisible(true);
            }
        });
        
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnExportarPDF;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnMasVendidos;
    private javax.swing.JButton btnReturn;
    private javax.swing.JComboBox<String> cbUsuario;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTable scrollTabla;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    // End of variables declaration//GEN-END:variables
}
