/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame_Interno;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.JFrame;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.awt.BorderLayout;

/**
 *
 * @author Gabriela
 */
public class ProveedorJinterno extends javax.swing.JFrame {

    /**
     * Creates new form ProveedorJinterno
     */
    public ProveedorJinterno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblBackenddelSabor = new javax.swing.JLabel();
        lblNomProveedor = new javax.swing.JLabel();
        lblNit = new javax.swing.JLabel();
        lblContacto = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblTelEmpresa = new javax.swing.JLabel();
        lblTelContacto = new javax.swing.JLabel();
        txtNomProveedor = new javax.swing.JTextField();
        txtNit = new javax.swing.JTextField();
        txtContacto = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelEmpresa = new javax.swing.JTextField();
        txtTelContacto = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));
        jPanel1.setForeground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabriela\\Documents\\NetBeansProjects\\Proyecto_Final\\src\\img\\logo.png")); // NOI18N
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 280));

        lblBackenddelSabor.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        lblBackenddelSabor.setForeground(new java.awt.Color(0, 0, 0));
        lblBackenddelSabor.setText("Backend del sabor");
        jPanel1.add(lblBackenddelSabor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        lblNomProveedor.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblNomProveedor.setForeground(new java.awt.Color(0, 0, 153));
        lblNomProveedor.setText("Nombre del proveedor:");
        jPanel1.add(lblNomProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        lblNit.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblNit.setForeground(new java.awt.Color(0, 0, 153));
        lblNit.setText("NIT");
        jPanel1.add(lblNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        lblContacto.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblContacto.setForeground(new java.awt.Color(0, 0, 153));
        lblContacto.setText("Contacto");
        jPanel1.add(lblContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        lblDireccion.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(0, 0, 153));
        lblDireccion.setText("Direccion");
        jPanel1.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        lblTelEmpresa.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblTelEmpresa.setForeground(new java.awt.Color(0, 0, 153));
        lblTelEmpresa.setText("Telefono de la Empresa");
        jPanel1.add(lblTelEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        lblTelContacto.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblTelContacto.setForeground(new java.awt.Color(0, 0, 153));
        lblTelContacto.setText("Telefono del Contacto");
        jPanel1.add(lblTelContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        txtNomProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(txtNomProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 260, -1));

        txtNit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNitActionPerformed(evt);
            }
        });
        jPanel1.add(txtNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 260, -1));
        jPanel1.add(txtContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 260, -1));
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 270, -1));

        txtTelEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelEmpresaActionPerformed(evt);
            }
        });
        jPanel1.add(txtTelEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 270, -1));
        jPanel1.add(txtTelContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 270, -1));

        btnSave.setBackground(new java.awt.Color(102, 255, 102));
        btnSave.setForeground(new java.awt.Color(0, 0, 0));
        btnSave.setText("Guardar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 90, 40));

        btnDelete.setBackground(new java.awt.Color(255, 153, 51));
        btnDelete.setForeground(new java.awt.Color(0, 0, 0));
        btnDelete.setText("Eliminar");
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 570, 80, 50));

        btnReturn.setBackground(new java.awt.Color(0, 204, 204));
        btnReturn.setForeground(new java.awt.Color(0, 0, 0));
        btnReturn.setText("Regresar");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        jPanel1.add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 570, 100, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNitActionPerformed

    private void txtTelEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelEmpresaActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReturnActionPerformed

    private void txtNomProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomProveedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProveedorJinterno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProveedorJinterno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProveedorJinterno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProveedorJinterno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProveedorJinterno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackenddelSabor;
    private javax.swing.JLabel lblContacto;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNit;
    private javax.swing.JLabel lblNomProveedor;
    private javax.swing.JLabel lblTelContacto;
    private javax.swing.JLabel lblTelEmpresa;
    private javax.swing.JTextField txtContacto;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtNomProveedor;
    private javax.swing.JTextField txtTelContacto;
    private javax.swing.JTextField txtTelEmpresa;
    // End of variables declaration//GEN-END:variables
}
